"""Generate Rust observe goldens from the committed trimmed SPK fixture.

The Rust tests load observe_de.bsp from this directory. Skyfield is asked for
Sun-only gravitational deflection so the reference matches the core reduction.
"""

from pathlib import Path

from skyfield.api import load, wgs84

HERE = Path(__file__).resolve().parent
KERNEL = HERE / "observe_de.bsp"

SITES = [
    ("greenwich", 51.4779, -0.0015, 46.0),
    ("sydney", -33.8568, 151.2153, 40.0),
]

CASES = [
    ("mars_greenwich", 4, "greenwich", (2024, 1, 1, 0, 0, 0)),
    ("jupiter_greenwich", 5, "greenwich", (2024, 1, 1, 0, 0, 0)),
    ("mars_sydney", 4, "sydney", (2024, 1, 1, 0, 0, 0)),
    ("jupiter_sydney", 5, "sydney", (2024, 1, 1, 0, 0, 0)),
    ("mars_near_conjunction", 4, "greenwich", (2023, 11, 18, 0, 0, 0)),
]


def fmt(value):
    return format(float(value), ".17e")


def render_equatorial(name, value):
    ra, dec, distance = value
    return (
        f"{name}: GoldenEquatorial {{ "
        f"ra_deg: {fmt(ra._degrees)}, "
        f"dec_deg: {fmt(dec.degrees)}, "
        f"distance_km: {fmt(distance.km)} }}"
    )


def render_horizontal(alt, az, distance):
    return (
        "horizontal: GoldenHorizontal { "
        f"az_deg: {fmt(az.degrees)}, "
        f"el_deg: {fmt(alt.degrees)}, "
        f"range_km: {fmt(distance.km)} }}"
    )


def render_ecliptic(lat, lon, distance):
    return (
        "ecliptic: GoldenEcliptic { "
        f"lon_deg: {fmt(lon.degrees)}, "
        f"lat_deg: {fmt(lat.degrees)}, "
        f"distance_km: {fmt(distance.km)} }}"
    )


def main():
    ts = load.timescale()
    eph = load(str(KERNEL))
    site_map = {
        name: eph[399] + wgs84.latlon(lat, lon, elevation_m=elevation_m)
        for name, lat, lon, elevation_m in SITES
    }

    print("// Generated by tests/fixtures/bodies/gen_observe_golden.py")
    print("// Source: observe_de.bsp with Skyfield, Sun-only deflection.")
    print("// Horizons spot check for Mars barycenter from Greenwich at")
    print("// 2024-01-01T00:00:00 UTC: apparent of-date RA/Dec agrees within")
    print("// the sub-arcsecond tolerance used below.")
    print("const OBSERVE_GOLDEN: &[ObserveGolden] = &[")
    for name, target, site_name, utc in CASES:
        y, mo, d, h, mi, s = utc
        t = ts.utc(y, mo, d, h, mi, s)
        astrometric = site_map[site_name].at(t).observe(eph[target])
        apparent = astrometric.apparent(deflectors=(10,))
        app_icrs = apparent.radec()
        app_date = apparent.radec(epoch="date")
        alt, az, alt_distance = apparent.altaz()
        ecl_lat, ecl_lon, ecl_distance = apparent.ecliptic_latlon(epoch="date")
        print("    ObserveGolden {")
        print(f'        name: "{name}",')
        print(f"        target_naif: {target},")
        print(f"        station: station_{site_name},")
        print(f"        utc: ({y}, {mo}, {d}, {h}, {mi}, {s}),")
        print(f"        {render_equatorial('astrometric', astrometric.radec())},")
        print(f"        {render_equatorial('apparent_icrs', app_icrs)},")
        print(f"        {render_equatorial('apparent', app_date)},")
        print(f"        {render_horizontal(alt, az, alt_distance)},")
        print(f"        {render_ecliptic(ecl_lat, ecl_lon, ecl_distance)},")
        print("    },")
    print("];")


if __name__ == "__main__":
    main()
